version: '3.8'

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0' -p '4000'"
    volumes:
      - .:/ie_statement_app
    depends_on:
      - postgres
    ports:
      - 4000:4000
    tty: true
    stdin_open: true
    env_file:
      - .env

  postgres:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
