name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.0
    - name: Run tests
      run: |
        gem install bundler
        bundle install
        bundle exec rubocop
        bin/rails zeitwerk:check
        brakeman -A --color
        bundle exec rspec
